[package]
name = "kvs"
version = "0.1.0"
authors = ["Reese Williams <reese@reesew.io>"]
description = "A command-line key-value store."
edition = "2018"

[dependencies.clap]
features = ["yaml"]
version = "2.33.0"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
