name: KVS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run against linter and formatter
      run: cargo clippy -- -D; cargo fmt -- --check
    - name: Run tests
      run: cargo test --verbose
    # TODO: Run benchmarks once they exist
